### ISSUE TITLE
Migrate to Modular JavaScript Project

### ISSUE THREAD

**Issue by priyanshuverma-dev** [prashasth-nair/Stocks-API#3]
Migrating Project in Modular pattern and formatting for better implementation.

**Comment by prashasth-nair** [comment]
@priyanshuverma-dev
Can u help me with changing title of the tab?

**Comment by priyanshuverma-dev** [comment]
Sure @prashasth-nair 
Add
```javascript
app.set('title', 'My Site');
```

**Comment by prashasth-nair** [comment]
> Sure @prashasth-nair Add
> 
> ```js
> app.set('title', 'My Site');
> ```

I already tried it. Its not working.

**Comment by priyanshuverma-dev** [comment]
@prashasth-nair i will create pr tomorrow

**Comment by prashasth-nair** [comment]
> @prashasth-nair i will create pr tomorrow

ya sure thanks

**Comment by priyanshuverma-dev** [comment]
It requires html to set title on the page but we are returning json so changing title is not possible 😞

**Comment by priyanshuverma-dev** [comment]
@prashasth-nair any other medium to communicate?

**Comment by prashasth-nair** [comment]
> @prashasth-nair any other medium to communicate?

do u have slack account?

**Comment by priyanshuverma-dev** [comment]
@prashasth-nair I have an idea that we can make a component based saas where user can embed component in websites. To discuss this idea share you whatsapp or signal number.

**Comment by prashasth-nair** [comment]
> @prashasth-nair I have an idea that we can make a component based saas where user can embed component in websites. To discuss this idea share you whatsapp or signal number.

Message me on signal: +919009468754
