### ISSUE TITLE
Infinite Loading 

### ISSUE THREAD

**Issue by programmer-rahul** [prashasth-nair/Stocks-API#6]
Nothing is working on home page , not login , signup just showing loading state

**Comment by prashasth-nair** [comment]
There is no singup and login.
Go to [stocks-api-qkyy.onrender.com/](https://stocks-api-qkyy.onrender.com/)
It should show:
![image](https://github.com/user-attachments/assets/abea98c4-44a7-4c90-8159-010c05369a2a)

**Comment by programmer-rahul** [comment]
Oh sorry i don't know how i opened issue here . I think i opened this issue here by accidently i was opening it in other repo.
